#!/bin/bash

mySeed=$1
nEvts=$2
globalTag=$3
JobName=step1_UndergroundCosmicSPLooseMu_${nEvts}_evts_seed_$mySeed

echo  "Job started at " `date`

CMSSW_DIR=${CMSSW_BASE}/src
LXBATCH_DIR=$PWD

cd ${CMSSW_BASE}/src
eval `scramv1 runtime -sh`
cd $LXBATCH_DIR

cp ${CMSSW_DIR}/UndergroundCosmicSPLooseMu_cfi_py_GEN_SIM_DIGI_L1_DIGI2RAW_RAW2DIGI_L1Reco_RECO_ALCA_Templ.py .
echo "cmsRun ${CMSSW_DIR}/UndergroundCosmicSPLooseMu_cfi_py_GEN_SIM_DIGI_L1_DIGI2RAW_RAW2DIGI_L1Reco_RECO_ALCA_Templ.py"

cmsRun UndergroundCosmicSPLooseMu_cfi_py_GEN_SIM_DIGI_L1_DIGI2RAW_RAW2DIGI_L1Reco_RECO_ALCA_Templ.py myseed=${mySeed} maxEvents=${nEvts} >& ${JobName}.out

echo "Content of working directory is: " `ls -lrt`

xrdcp -f step1_UndergroundCosmicSPLooseMu_${globalTag}_${nEvts}_evts_seed_${mySeed}.root root://eoscms.cern.ch//store/group/alca_trackeralign/musich/test_out/Cosmics2018MCProd/step1_UndergroundCosmicSPLooseMu_${globalTag}_${nEvts}_evts_seed_${mySeed}.root
cp ${JobName}.out ${CMSSW_DIR}/outfiles

echo  "Job ended at " `date`

exit 0