universe              = vanilla
arguments             = $(par1) $(par2) $(par3) $(par4)
executable            = WM_13TeV_TuneCUETP8M1cfi_GEN_SIM_DIGI_L1_DIGI2RAW_RAW2DIGI_L1Reco_RECO_ALCA_Templ.sh
output                = $(par4)/outfiles/step1_WM_13TeV_TuneCUETP8M1$(par2)_evts_seed_$(par1).out
error                 = $(par4)/outfiles/step1_WM_13TeV_TuneCUETP8M1$(par2)_evts_seed_$(par1).err
log                   = $(par4)/outfiles/step1_WM_13TeV_TuneCUETP8M1$(par2)_evts_seed_$(par1).log
transfer_output_files = ""
+JobFlavour = "workday" 
queue